name: orghub
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  intl_translation: any
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  localize_and_translate: 
  share: ^0.6.3+1
  flutter_rating_bar: ^3.0.0
  auto_size_text: ^2.1.0
  pin_code_fields: ^3.0.1
  toast: ^0.1.5
  url_launcher:  ^5.0.3
  dio: any
  flash: ^1.3.1
  flutter_rating: ^0.0.2
  dotted_border: ^1.0.5
  google_maps_flutter: ^0.5.21+15
  shimmer: ^1.1.1
  location: ^3.0.2
  lazy_load_scrollview: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  get: ^3.2.0
  flutter_typeahead: ^1.8.5
  # flutter_chips_input: ^1.9.0-dev.1
  flutter_chips_input: ^1.9.4
  datetime_picker_formfield: ^1.0.0
  signature: ^3.1.1
  validators: ^2.0.0+1
  date_range_picker: ^1.0.6
  flutter_touch_spin: 
  # image_picker: ^0.6.7+4
  image_picker: ^0.6.7+12
  rating_bar: ^0.2.0
  phone_number: ^0.6.2+3
  group_radio_button: ^1.0.1
  flutter_speed_dial: ^1.2.5
  rxdart: ^0.24.1
  ulid: ^1.1.0
  path_provider: 
  flutter_audio_recorder: ^0.5.5
  file: 
  audioplayers: ^0.13.2
  flutter_bloc: ^5.0.1
  quick_log: ^1.1.3
  kiwi: ^2.0.0
  # google_map_location_picker: ^3.3.3
  path: ^1.7.0
  flutter_swiper: ^1.1.6
  jiffy: 
  after_layout: ^1.0.7+2
  file_picker: ^1.13.0+1
  modal_bottom_sheet: ^0.2.0+1
  permission_handler: ^5.0.1+1
  http: ^0.12.2
  flutter_html: ^0.11.1
  laravel_echo: ^0.2.2
  socket_io_client: ^0.9.11
  file_utils: ^0.1.4
  open_file: ^3.0.1
  flutter_slidable: ^0.5.5
  # firebase_messaging: ^7.0.0
  firebase_messaging: ^7.0.2
  geocoding: ^1.0.5
  multi_image_picker: ^4.7.14
  http_parser: ^3.1.4
  flutter_image_compress: ^0.7.0
  bloc: ^5.0.1
  get_it: ^5.0.1
  

dependency_overrides:
  intl: 
  country_pickers: ^1.3.0
  geolocator: ^6.1.1
  firebase_core:


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/langs/en.json
    - assets/langs/ar.json


  fonts:
    - family: Neosans
      fonts:
        - asset: assets/fonts/neosans-Regular.otf

    - family: Neosans-Bold
      fonts:
        - asset: assets/fonts/neosans_bold.otf