class GetMostBuyingAdvertsEvents {}
class GetMostBuyingAdvertsEventsStart extends GetMostBuyingAdvertsEvents {}
class GetMostBuyingAdvertsEventsSuccess extends GetMostBuyingAdvertsEvents {}
class GetMostBuyingAdvertsEventsFailed extends GetMostBuyingAdvertsEvents {}
